model:
  base_learning_rate: 1.0e-4 
  target: cldm.cldm.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    control_key: "hint"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: #val/loss_simple_ema
    scale_factor: 0.18215
    only_mid_control: False
    sd_locked: True #False 
    use_ema: True #False
    ckpt_path: "pretrained_models/control_sd20_ini.ckpt"
    reset_ema: True 
    reset_num_ema_updates: false
    keep_num_ema_updates: false 
    only_model: false 
    log_all_grad_norm: True
    sep_lr: True
    decoder_lr: 1.0e-4 
    sep_cond_txt: True 
    exchange_cond_txt: False

    scheduler_config: 
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1 ] # NOTE 1 for resuming. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    control_stage_config:
      target: cldm.cldm.ControlNet
      params:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    unet_config:
      target: cldm.cldm.ControlledUnetModel
      params:
        use_checkpoint: True
        # use_fp16: True # False
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPSepEncoder
      params:
        freeze: True
        layer: "penultimate"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16 # (halve gradually if OOM for large batch size)
    num_workers: 2 
    wrap: False
    custom_collate: True
    train:
      target: ldm.data.laion_glyph_control.LAIONGlyphCLDataset
      params:
        control_key: "hint"
        no_hint: False
        BLIP_caption: True
        new_proc_config:
          target: ldm.data.util.new_process_im_base
          params:
            size: 512
            interpolation: 3 
            do_flip: False 
            hint_range_m11: False
        rendered_txt_in_caption: False
        caption_choices: ["original", "original"] 
        caption_drop_rates: [0.1, 0.5] 
        rm_text_from_cp: False
        replace_token: ""


lightning:
  callbacks:
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params: 
        every_n_train_steps: 1000 

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params: 
      save_top_k: -1  
  trainer:
    benchmark: True
    # max_epochs: 100 
    accumulate_grad_batches: 2 # (set > 1 if OOM for large batch size)
    deterministic: True
    profiler: "simple"
    log_every_n_steps: 3
    # num_nodes: 8 